### ISSUE TITLE
How do you get geolocation ?

### ISSUE THREAD

**Issue by Oxey405** [zeke/geotail#1]
Hello @zeke !
I'm making a map application and I want to get the precise location of the user. (With is agreement)
Could you please explain how you did that with your application ? (If it works I put you in the credits as well !)

**Comment by zeke** [comment]
This project uses the https://github.com/maxogden/geolocation-stream package.

That package in turn uses the Geolocation API that's built into web browsers: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

Good luck on your project!
